/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.70"

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions {
        jvmTarget = "1.8"
    }
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
    mavenCentral()
}

dependencies {
    // Kotlin
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Hashing
    implementation("com.rfksystems:blake2b:1.0.0")

    // Utils
    implementation("commons-codec:commons-codec:1.14")
    implementation("io.reactivex.rxjava3:rxjava:3.0.9")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-rx3:1.4.2")

    // Networking
    implementation("io.ktor:ktor-client-core:1.5.0")
    implementation("io.ktor:ktor-client-cio:1.5.0")
    implementation("io.ktor:ktor-client-gson:1.5.0")
    implementation("io.ktor:ktor-client-logging:1.5.0")
    implementation("io.ktor:ktor-client-auth:1.5.0")

    // Blockchain
    implementation("org.web3j:core:4.7.0")


    // Testing
    testImplementation("org.jetbrains.kotlin:kotlin-test")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
    testImplementation("io.ktor:ktor-client-mock:1.5.0")
    testImplementation("org.web3j:web3j-unit:4.7.0")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.7.0")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.0")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.7.0")
}
