name: Bloock Kotlin SDK CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version:
          - "8"
          - "11"
          - "13"
          - "15"

    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@master
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}
      - name: Display version
        run: ./gradlew --version
      - name: Build artifacts
        run: ./gradlew assemble
      - name: Unit test
        run: ./gradlew check
      - name: Integration test
        run: API_KEY=${{ secrets.API_KEY }} API_HOST=${{ secrets.API_HOST }} ./gradlew integrationTest
  publish:
    runs-on: ubuntu-latest
    needs: tests
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: '15'
      - name: Publish
        env:
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          PGP_KEY_ID: ${{ secrets.PGP_KEY_ID }}
          PGP_SIGNING_KEY: ${{ secrets.PGP_SIGNING_KEY }}
          PGP_SIGNING_PASSWORD: ${{ secrets.PGP_SIGNING_PASSWORD }}
        run: ./gradlew publish
