name: Bloock Kotlin SDK CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version:
          - "8"
          - "11"
          - "13"
          - "15"

    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@master
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}
      - name: Display version
        run: ./gradlew --version
      - name: Build artifacts
        run: ./gradlew assemble
      - name: Unit test
        run: ./gradlew check
      - name: Integration test
        run: API_KEY=${{ secrets.API_KEY }} ./gradlew integrationTest
  publish:
    runs-on: ubuntu-latest
    needs: tests
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: '15'
      - name: Publish
        run: ./gradlew -PMAVEN_UPLOAD_USER=${{ secrets.MAVEN_UPLOAD_USER }} -PMAVEN_UPLOAD_PWD=${{ secrets.MAVEN_UPLOAD_PWD }}  -PPGP_SIGNING_KEY="${{ secrets.PGP_SIGNING_KEY }}" -PPGP_SIGNING_PASSWORD="${{ secrets.PGP_SIGNING_PASSWORD }}" publish
